version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: nestjsrealworld
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dbdata:
    driver: local
